---

- name: Install Homebrew Cask packages
  homebrew_cask: >
    name={{ item.name | default(item) }}
    state={{ item.state | default('present') }}
  with_items: homebrew_cask_packages
  when: homebrew_cask_packages